# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ed6b4e8855631419a7032e6e72b9d8414371de44a1c33af33648a6b2b845cee37af9a9a703a8a76e52c2962b2f79a97361054d99cf8dde0dfddb2cb5e8b265

test:
  secret_key_base: 81e6cf82c9fd111ebf8fc0de468620c1dc48e71be21d83042c668a6a00c85e23fe9e5e512c3cc51e1dc8bd683b2799567abdcaacd5dcab53e61ce144b0db9d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
